# Generated by Django 5.1.7 on 2025-04-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0008_useravatar_userbackground"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbackground",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserAvatar",
        ),
        migrations.DeleteModel(
            name="UserBackground",
        ),
    ]
