# Generated by Django 5.1.7 on 2025-04-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0010_useravatar_userbackground"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetime",
            name="recording_path",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="course_recordings/%Y/%m/%d/",
                verbose_name="课程录像",
            ),
        ),
    ]
