# Generated by Django 5.1.7 on 2025-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_management", "0011_coursetime_recording_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetime",
            name="emotion_analysis_json",
            field=models.JSONField(blank=True, null=True, verbose_name="情绪分析数据"),
        ),
        migrations.AddField(
            model_name="coursetime",
            name="processed_recording_path",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="processed_recordings/%Y/%m/%d/",
                verbose_name="处理后的录像",
            ),
        ),
    ]
