# Generated by Django 5.1.7 on 2025-05-21 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advanced_features", "0001_initial"),
        ("course_management", "0012_coursetime_emotion_analysis_json_and_more"),
        (
            "user_management",
            "0009_remove_userbackground_user_delete_useravatar_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="课堂成绩",
                    ),
                ),
                (
                    "homework_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="作业成绩",
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="考试成绩",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("2023-2024-1", "2023-2024学年第一学期"),
                            ("2023-2024-2", "2023-2024学年第二学期"),
                            ("2024-2025-1", "2024-2025学年第一学期"),
                            ("2024-2025-2", "2024-2025学年第二学期"),
                        ],
                        help_text="选择学期",
                        max_length=50,
                        verbose_name="学期",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_records",
                        to="course_management.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_records",
                        to="user_management.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩记录",
                "verbose_name_plural": "成绩记录",
                "ordering": ["student", "course"],
                "unique_together": {("student", "course", "semester")},
            },
        ),
    ]
